# -*- coding: utf-8 -*-
"""fizzbuzz.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itQq8gs04IpnW0XCCWNvKIM2Zf98fnsT
"""

#Start a loop so it keeps asking for the user to input a number
while True:
  user_number = input("Enter a number: ")   #Has the user input a number(this is a string)

  number = int(user_number)       #The int changes the user's input from a string to an integer

  if number % 3 == 0 and number % 5 == 0:    #Checks if the number is divisible by 3 AND 5
    print("FizzBuzz")

  elif number % 3 == 0:    #Checks if the number is divisible by 3 ONLY
    print("Fizz")

  elif number % 5 == 0:    #Checks if the number is divisible by 5 ONLY
    print("Buzz")

  else:                    #If the number isn't divisble by 3 or 5 then the loop ends and this like an "exit"
       break